<?php
/**
 * Classifieds.
 *
 * @copyright Ralf Koester (Rallek)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Classifieds
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Configuration handler implementation class.
 */
class Classifieds_Form_Handler_Admin_Config extends Classifieds_Form_Handler_Admin_Base_Config
{
    // feel free to extend the base handler class here
}
