<?php
/**
 * Classifieds.
 *
 * @copyright Ralf Koester (Rallek)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Classifieds
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo;
use DoctrineExtensions\StandardFields\Mapping\Annotation as ZK;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the base entity class for classified entities.
 *
 * @abstract
 */
abstract class Classifieds_Entity_Base_Classified extends Zikula_EntityAccess
{
    /**
     * @var string The tablename this object maps to.
     */
    protected $_objectType = 'classified';
    
    /**
     * @var Classifieds_Entity_Validator_Classified The validator for this entity.
     */
    protected $_validator = null;
    
    /**
     * @var boolean Option to bypass validation if needed.
     */
    protected $_bypassValidation = false;
    
    /**
     * @var array List of available item actions.
     */
    protected $_actions = array();
    
    /**
     * @var array The current workflow data of this object.
     */
    protected $__WORKFLOW__ = array();
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer", unique=true)
     * @var integer $id.
     */
    protected $id = 0;
    
    /**
     * @ORM\Column(length=20)
     * @var string $workflowState.
     */
    protected $workflowState = 'initial';
    
    /**
     * @ORM\Column(length=255)
     * @var string $title.
     */
    protected $title = '';
    
    /**
     * @ORM\Column(length=255)
     * @var string $kind.
     */
    protected $kind = null;
    
    /**
     * @ORM\Column(type="text", length=2000)
     * @var text $description.
     */
    protected $description = '';
    
    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     * @var decimal $price.
     */
    protected $price = 0.00;
    
    /**
     * @ORM\Column(length=255)
     * @var string $email.
     */
    protected $email = '';
    
    /**
     * @ORM\Column(length=255)
     * @var string $fon.
     */
    protected $fon = '';
    
    /**
     * Picture meta data array.
     *
     * @ORM\Column(type="array")
     * @var array $pictureMeta.
     */
    protected $pictureMeta = array();
    
    /**
     * @ORM\Column(length=255)
     * @var string $picture.
     */
    protected $picture = '';
    
    /**
     * The full path to the picture.
     *
     * @var string $pictureFullPath.
     */
    protected $pictureFullPath = '';
    
    /**
     * Full picture path as url.
     *
     * @var string $pictureFullPathUrl.
     */
    protected $pictureFullPathUrl = '';
    /**
     * Picture2 meta data array.
     *
     * @ORM\Column(type="array")
     * @var array $picture2Meta.
     */
    protected $picture2Meta = array();
    
    /**
     * @ORM\Column(length=255)
     * @var string $picture2.
     */
    protected $picture2 = '';
    
    /**
     * The full path to the picture2.
     *
     * @var string $picture2FullPath.
     */
    protected $picture2FullPath = '';
    
    /**
     * Full picture2 path as url.
     *
     * @var string $picture2FullPathUrl.
     */
    protected $picture2FullPathUrl = '';
    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     * @var DateTime $classifiedStart.
     */
    protected $classifiedStart = null;
    
    /**
     * @ORM\Column(type="datetime")
     * @var DateTime $classifiedEnd.
     */
    protected $classifiedEnd = null;
    
    /**
     * @ORM\Column(type="boolean")
     * @var boolean $terms.
     */
    protected $terms = false;
    
    
    /**
     * @ORM\OneToMany(targetEntity="Classifieds_Entity_ClassifiedCategory", 
     *                mappedBy="entity", cascade={"all"}, 
     *                orphanRemoval=true)
     * @var Classifieds_Entity_ClassifiedCategory
     */
    protected $categories = null;
    
    /**
     * @ORM\Column(type="integer")
     * @ZK\StandardFields(type="userid", on="create")
     * @var integer $createdUserId.
     */
    protected $createdUserId;
    
    /**
     * @ORM\Column(type="integer")
     * @ZK\StandardFields(type="userid", on="update")
     * @var integer $updatedUserId.
     */
    protected $updatedUserId;
    
    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     * @var datetime $createdDate.
     */
    protected $createdDate;
    
    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="update")
     * @var datetime $updatedDate.
     */
    protected $updatedDate;
    
    
    /**
     * Constructor.
     * Will not be called by Doctrine and can therefore be used
     * for own implementation purposes. It is also possible to add
     * arbitrary arguments as with every other class method.
     *
     * @param TODO
     */
    public function __construct()
    {
        $this->classifiedEnd = \DateTime::createFromFormat('Y-m-d H:i:s', date('Y-m-d H:i:s'));
        
        $serviceManager = ServiceUtil::getManager();
        $listHelper = new Classifieds_Util_ListEntries($serviceManager);
        
        $items = array();
        $listEntries = $listHelper->getKindEntriesForClassified();
        foreach ($listEntries as $listEntry) {
            if ($listEntry['default'] === true) {
                $items[] = $listEntry['value'];
            }
        }
        $this->kind = implode('###', $items);
        
        $this->workflowState = 'initial';
        $this->initValidator();
        $this->initWorkflow();
        $this->categories = new ArrayCollection();
    }
    
    /**
     * Get _object type.
     *
     * @return string
     */
    public function get_objectType()
    {
        return $this->_objectType;
    }
    
    /**
     * Set _object type.
     *
     * @param string $_objectType.
     *
     * @return void
     */
    public function set_objectType($_objectType)
    {
        $this->_objectType = $_objectType;
    }
    
    /**
     * Get _validator.
     *
     * @return Classifieds_Entity_Validator_Classified
     */
    public function get_validator()
    {
        return $this->_validator;
    }
    
    /**
     * Set _validator.
     *
     * @param Classifieds_Entity_Validator_Classified $_validator.
     *
     * @return void
     */
    public function set_validator(Classifieds_Entity_Validator_Classified $_validator = null)
    {
        $this->_validator = $_validator;
    }
    
    /**
     * Get _bypass validation.
     *
     * @return boolean
     */
    public function get_bypassValidation()
    {
        return $this->_bypassValidation;
    }
    
    /**
     * Set _bypass validation.
     *
     * @param boolean $_bypassValidation.
     *
     * @return void
     */
    public function set_bypassValidation($_bypassValidation)
    {
        $this->_bypassValidation = $_bypassValidation;
    }
    
    /**
     * Get _actions.
     *
     * @return array
     */
    public function get_actions()
    {
        return $this->_actions;
    }
    
    /**
     * Set _actions.
     *
     * @param array $_actions.
     *
     * @return void
     */
    public function set_actions(array $_actions = Array())
    {
        $this->_actions = $_actions;
    }
    
    /**
     * Get __ w o r k f l o w__.
     *
     * @return array
     */
    public function get__WORKFLOW__()
    {
        return $this->__WORKFLOW__;
    }
    
    /**
     * Set __ w o r k f l o w__.
     *
     * @param array $__WORKFLOW__.
     *
     * @return void
     */
    public function set__WORKFLOW__(array $__WORKFLOW__ = Array())
    {
        $this->__WORKFLOW__ = $__WORKFLOW__;
    }
    
    
    /**
     * Get id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * Set id.
     *
     * @param integer $id.
     *
     * @return void
     */
    public function setId($id)
    {
        if ($id != $this->id) {
            $this->id = $id;
        }
    }
    
    /**
     * Get workflow state.
     *
     * @return string
     */
    public function getWorkflowState()
    {
        return $this->workflowState;
    }
    
    /**
     * Set workflow state.
     *
     * @param string $workflowState.
     *
     * @return void
     */
    public function setWorkflowState($workflowState)
    {
        if ($workflowState != $this->workflowState) {
            $this->workflowState = $workflowState;
        }
    }
    
    /**
     * Get title.
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }
    
    /**
     * Set title.
     *
     * @param string $title.
     *
     * @return void
     */
    public function setTitle($title)
    {
        if ($title != $this->title) {
            $this->title = $title;
        }
    }
    
    /**
     * Get kind.
     *
     * @return string
     */
    public function getKind()
    {
        return $this->kind;
    }
    
    /**
     * Set kind.
     *
     * @param string $kind.
     *
     * @return void
     */
    public function setKind($kind)
    {
        if ($kind != $this->kind) {
            $this->kind = $kind;
        }
    }
    
    /**
     * Get description.
     *
     * @return text
     */
    public function getDescription()
    {
        return $this->description;
    }
    
    /**
     * Set description.
     *
     * @param text $description.
     *
     * @return void
     */
    public function setDescription($description)
    {
        if ($description != $this->description) {
            $this->description = $description;
        }
    }
    
    /**
     * Get price.
     *
     * @return decimal
     */
    public function getPrice()
    {
        return $this->price;
    }
    
    /**
     * Set price.
     *
     * @param decimal $price.
     *
     * @return void
     */
    public function setPrice($price)
    {
        if ($price != $this->price) {
            $this->price = $price;
        }
    }
    
    /**
     * Get email.
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }
    
    /**
     * Set email.
     *
     * @param string $email.
     *
     * @return void
     */
    public function setEmail($email)
    {
        if ($email != $this->email) {
            $this->email = $email;
        }
    }
    
    /**
     * Get fon.
     *
     * @return string
     */
    public function getFon()
    {
        return $this->fon;
    }
    
    /**
     * Set fon.
     *
     * @param string $fon.
     *
     * @return void
     */
    public function setFon($fon)
    {
        if ($fon != $this->fon) {
            $this->fon = $fon;
        }
    }
    
    /**
     * Get picture.
     *
     * @return string
     */
    public function getPicture()
    {
        return $this->picture;
    }
    
    /**
     * Set picture.
     *
     * @param string $picture.
     *
     * @return void
     */
    public function setPicture($picture)
    {
        if ($picture != $this->picture) {
            $this->picture = $picture;
        }
    }
    
    /**
     * Get picture full path.
     *
     * @return string
     */
    public function getPictureFullPath()
    {
        return $this->pictureFullPath;
    }
    
    /**
     * Set picture full path.
     *
     * @param string $pictureFullPath.
     *
     * @return void
     */
    public function setPictureFullPath($pictureFullPath)
    {
        if ($pictureFullPath != $this->pictureFullPath) {
            $this->pictureFullPath = $pictureFullPath;
        }
    }
    
    /**
     * Get picture full path url.
     *
     * @return string
     */
    public function getPictureFullPathUrl()
    {
        return $this->pictureFullPathUrl;
    }
    
    /**
     * Set picture full path url.
     *
     * @param string $pictureFullPathUrl.
     *
     * @return void
     */
    public function setPictureFullPathUrl($pictureFullPathUrl)
    {
        if ($pictureFullPathUrl != $this->pictureFullPathUrl) {
            $this->pictureFullPathUrl = $pictureFullPathUrl;
        }
    }
    
    /**
     * Get picture meta.
     *
     * @return array
     */
    public function getPictureMeta()
    {
        return $this->pictureMeta;
    }
    
    /**
     * Set picture meta.
     *
     * @param array $pictureMeta.
     *
     * @return void
     */
    public function setPictureMeta($pictureMeta = Array())
    {
        if ($pictureMeta != $this->pictureMeta) {
            $this->pictureMeta = $pictureMeta;
        }
    }
    
    /**
     * Get picture2.
     *
     * @return string
     */
    public function getPicture2()
    {
        return $this->picture2;
    }
    
    /**
     * Set picture2.
     *
     * @param string $picture2.
     *
     * @return void
     */
    public function setPicture2($picture2)
    {
        if ($picture2 != $this->picture2) {
            $this->picture2 = $picture2;
        }
    }
    
    /**
     * Get picture2 full path.
     *
     * @return string
     */
    public function getPicture2FullPath()
    {
        return $this->picture2FullPath;
    }
    
    /**
     * Set picture2 full path.
     *
     * @param string $picture2FullPath.
     *
     * @return void
     */
    public function setPicture2FullPath($picture2FullPath)
    {
        if ($picture2FullPath != $this->picture2FullPath) {
            $this->picture2FullPath = $picture2FullPath;
        }
    }
    
    /**
     * Get picture2 full path url.
     *
     * @return string
     */
    public function getPicture2FullPathUrl()
    {
        return $this->picture2FullPathUrl;
    }
    
    /**
     * Set picture2 full path url.
     *
     * @param string $picture2FullPathUrl.
     *
     * @return void
     */
    public function setPicture2FullPathUrl($picture2FullPathUrl)
    {
        if ($picture2FullPathUrl != $this->picture2FullPathUrl) {
            $this->picture2FullPathUrl = $picture2FullPathUrl;
        }
    }
    
    /**
     * Get picture2 meta.
     *
     * @return array
     */
    public function getPicture2Meta()
    {
        return $this->picture2Meta;
    }
    
    /**
     * Set picture2 meta.
     *
     * @param array $picture2Meta.
     *
     * @return void
     */
    public function setPicture2Meta($picture2Meta = Array())
    {
        if ($picture2Meta != $this->picture2Meta) {
            $this->picture2Meta = $picture2Meta;
        }
    }
    
    /**
     * Get classified start.
     *
     * @return DateTime
     */
    public function getClassifiedStart()
    {
        return $this->classifiedStart;
    }
    
    /**
     * Set classified start.
     *
     * @param DateTime $classifiedStart.
     *
     * @return void
     */
    public function setClassifiedStart($classifiedStart)
    {
        if ($classifiedStart != $this->classifiedStart) {
            if (is_object($classifiedStart) && $classifiedStart instanceOf \DateTime) {
                $this->classifiedStart = $classifiedStart;
            } else {
                $this->classifiedStart = new \DateTime($classifiedStart);
            }
        }
    }
    
    /**
     * Get classified end.
     *
     * @return DateTime
     */
    public function getClassifiedEnd()
    {
        return $this->classifiedEnd;
    }
    
    /**
     * Set classified end.
     *
     * @param DateTime $classifiedEnd.
     *
     * @return void
     */
    public function setClassifiedEnd($classifiedEnd)
    {
        if ($classifiedEnd != $this->classifiedEnd) {
            if (is_object($classifiedEnd) && $classifiedEnd instanceOf \DateTime) {
                $this->classifiedEnd = $classifiedEnd;
            } else {
                $this->classifiedEnd = new \DateTime($classifiedEnd);
            }
        }
    }
    
    /**
     * Get terms.
     *
     * @return boolean
     */
    public function getTerms()
    {
        return $this->terms;
    }
    
    /**
     * Set terms.
     *
     * @param boolean $terms.
     *
     * @return void
     */
    public function setTerms($terms)
    {
        if ($terms !== $this->terms) {
            $this->terms = (bool)$terms;
        }
    }
    
    /**
     * Get categories.
     *
     * @return array
     */
    public function getCategories()
    {
        return $this->categories;
    }
    
    /**
     * Set categories.
     *
     * @param array $categories.
     *
     * @return void
     */
    public function setCategories($categories)
    {
        $this->categories = $categories;
    }
    
    /**
     * Get created user id.
     *
     * @return integer
     */
    public function getCreatedUserId()
    {
        return $this->createdUserId;
    }
    
    /**
     * Set created user id.
     *
     * @param integer $createdUserId.
     *
     * @return void
     */
    public function setCreatedUserId($createdUserId)
    {
        $this->createdUserId = $createdUserId;
    }
    
    /**
     * Get updated user id.
     *
     * @return integer
     */
    public function getUpdatedUserId()
    {
        return $this->updatedUserId;
    }
    
    /**
     * Set updated user id.
     *
     * @param integer $updatedUserId.
     *
     * @return void
     */
    public function setUpdatedUserId($updatedUserId)
    {
        $this->updatedUserId = $updatedUserId;
    }
    
    /**
     * Get created date.
     *
     * @return datetime
     */
    public function getCreatedDate()
    {
        return $this->createdDate;
    }
    
    /**
     * Set created date.
     *
     * @param datetime $createdDate.
     *
     * @return void
     */
    public function setCreatedDate($createdDate)
    {
        $this->createdDate = $createdDate;
    }
    
    /**
     * Get updated date.
     *
     * @return datetime
     */
    public function getUpdatedDate()
    {
        return $this->updatedDate;
    }
    
    /**
     * Set updated date.
     *
     * @param datetime $updatedDate.
     *
     * @return void
     */
    public function setUpdatedDate($updatedDate)
    {
        $this->updatedDate = $updatedDate;
    }
    
    
    
    /**
     * Initialise validator and return it's instance.
     *
     * @return Classifieds_Entity_Validator_Classified The validator for this entity.
     */
    public function initValidator()
    {
        if (!is_null($this->_validator)) {
            return $this->_validator;
        }
        $this->_validator = new Classifieds_Entity_Validator_Classified($this);
    
        return $this->_validator;
    }
    
    /**
     * Sets/retrieves the workflow details.
     *
     * @param boolean $forceLoading load the workflow record.
     */
    public function initWorkflow($forceLoading = false)
    {
        $currentFunc = FormUtil::getPassedValue('func', 'main', 'GETPOST', FILTER_SANITIZE_STRING);
        $isReuse = FormUtil::getPassedValue('astemplate', '', 'GETPOST', FILTER_SANITIZE_STRING);
    
        // apply workflow with most important information
        $idColumn = 'id';
        $workflowHelper = new Classifieds_Util_Workflow(ServiceUtil::getManager());
        $schemaName = $workflowHelper->getWorkflowName($this['_objectType']);
        $this['__WORKFLOW__'] = array(
            'state' => $this['workflowState'],
            'obj_table' => $this['_objectType'],
            'obj_idcolumn' => $idColumn,
            'obj_id' => $this[$idColumn],
            'schemaname' => $schemaName);
        
        // load the real workflow only when required (e. g. when func is edit or delete)
        if ((!in_array($currentFunc, array('main', 'view', 'display')) && empty($isReuse)) || $forceLoading) {
            $result = Zikula_Workflow_Util::getWorkflowForObject($this, $this['_objectType'], $idColumn, 'Classifieds');
            if (!$result) {
                $dom = ZLanguage::getModuleDomain('Classifieds');
                LogUtil::registerError(__('Error! Could not load the associated workflow.', $dom));
            }
        }
        
        if (!is_object($this['__WORKFLOW__']) && !isset($this['__WORKFLOW__']['schemaname'])) {
            $workflow = $this['__WORKFLOW__'];
            $workflow['schemaname'] = $schemaName;
            $this['__WORKFLOW__'] = $workflow;
        }
    }
    
    /**
     * Resets workflow data back to initial state.
     * To be used after cloning an entity object.
     */
    public function resetWorkflow()
    {
        $this->setWorkflowState('initial');
        $workflowHelper = new Classifieds_Util_Workflow(ServiceUtil::getManager());
        $schemaName = $workflowHelper->getWorkflowName($this['_objectType']);
        $this['__WORKFLOW__'] = array(
            'state' => $this['workflowState'],
            'obj_table' => $this['_objectType'],
            'obj_idcolumn' => 'id',
            'obj_id' => 0,
            'schemaname' => $schemaName);
    }
    
    /**
     * Start validation and raise exception if invalid data is found.
     *
     * @return void.
     *
     * @throws Zikula_Exception Thrown if a validation error occurs
     */
    public function validate()
    {
        if ($this->_bypassValidation === true) {
            return;
        }
    
        // decode possibly encoded mail addresses (#201)
    if (strpos($this['email'], '&#') !== false) {
        $this['email'] = html_entity_decode($this['email']);
    }
        $result = $this->initValidator()->validateAll();
        if (is_array($result)) {
            throw new Zikula_Exception($result['message'], $result['code'], $result['debugArray']);
        }
    }
    
    /**
     * Return entity data in JSON format.
     *
     * @return string JSON-encoded data.
     */
    public function toJson()
    {
        return json_encode($this->toArray());
    }
    
    /**
     * Collect available actions for this entity.
     */
    protected function prepareItemActions()
    {
        if (!empty($this->_actions)) {
            return;
        }
    
        $currentType = FormUtil::getPassedValue('type', 'user', 'GETPOST', FILTER_SANITIZE_STRING);
        $currentFunc = FormUtil::getPassedValue('func', 'main', 'GETPOST', FILTER_SANITIZE_STRING);
        $dom = ZLanguage::getModuleDomain('Classifieds');
        if ($currentType == 'admin') {
            if (in_array($currentFunc, array('main', 'view'))) {
                $this->_actions[] = array(
                    'url' => array('type' => 'user', 'func' => 'display', 'arguments' => array('ot' => 'classified', 'id' => $this['id'])),
                    'icon' => 'preview',
                    'linkTitle' => __('Open preview page', $dom),
                    'linkText' => __('Preview', $dom)
                );
                $this->_actions[] = array(
                    'url' => array('type' => 'admin', 'func' => 'display', 'arguments' => array('ot' => 'classified', 'id' => $this['id'])),
                    'icon' => 'display',
                    'linkTitle' => str_replace('"', '', $this->getTitleFromDisplayPattern()),
                    'linkText' => __('Details', $dom)
                );
            }
            if (in_array($currentFunc, array('main', 'view', 'display'))) {
                $component = 'Classifieds:Classified:';
                $instance = $this->id . '::';
                if (SecurityUtil::checkPermission($component, $instance, ACCESS_DELETE)) {
                    $this->_actions[] = array(
                        'url' => array('type' => 'admin', 'func' => 'delete', 'arguments' => array('ot' => 'classified', 'id' => $this['id'])),
                        'icon' => 'delete',
                        'linkTitle' => __('Delete', $dom),
                        'linkText' => __('Delete', $dom)
                    );
                }
            }
            if ($currentFunc == 'display') {
                $this->_actions[] = array(
                    'url' => array('type' => 'admin', 'func' => 'view', 'arguments' => array('ot' => 'classified')),
                    'icon' => 'back',
                    'linkTitle' => __('Back to overview', $dom),
                    'linkText' => __('Back to overview', $dom)
                );
            }
        }
        if ($currentType == 'user') {
            if (in_array($currentFunc, array('main', 'view'))) {
                $this->_actions[] = array(
                    'url' => array('type' => 'user', 'func' => 'display', 'arguments' => array('ot' => 'classified', 'id' => $this['id'])),
                    'icon' => 'display',
                    'linkTitle' => str_replace('"', '', $this->getTitleFromDisplayPattern()),
                    'linkText' => __('Details', $dom)
                );
            }
            if (in_array($currentFunc, array('main', 'view', 'display'))) {
                $component = 'Classifieds:Classified:';
                $instance = $this->id . '::';
                if (SecurityUtil::checkPermission($component, $instance, ACCESS_EDIT)) {
                    // only allow editing for the owner or people with higher permissions
                    if ($this['createdUserId'] == UserUtil::getVar('uid') || SecurityUtil::checkPermission($component, $instance, ACCESS_ADD)) {
                        $this->_actions[] = array(
                            'url' => array('type' => 'user', 'func' => 'edit', 'arguments' => array('ot' => 'classified', 'id' => $this['id'])),
                            'icon' => 'edit',
                            'linkTitle' => __('Edit', $dom),
                            'linkText' => __('Edit', $dom)
                        );
                        $this->_actions[] = array(
                            'url' => array('type' => 'user', 'func' => 'edit', 'arguments' => array('ot' => 'classified', 'astemplate' => $this['id'])),
                            'icon' => 'saveas',
                            'linkTitle' => __('Reuse for new item', $dom),
                            'linkText' => __('Reuse', $dom)
                        );
                    }
                }
            }
            if ($currentFunc == 'display') {
                $this->_actions[] = array(
                    'url' => array('type' => 'user', 'func' => 'view', 'arguments' => array('ot' => 'classified')),
                    'icon' => 'back',
                    'linkTitle' => __('Back to overview', $dom),
                    'linkText' => __('Back to overview', $dom)
                );
            }
        }
    }
    
    /**
     * Creates url arguments array for easy creation of display urls.
     *
     * @return Array The resulting arguments list.
     */
    public function createUrlArgs()
    {
        $args = array('ot' => $this['_objectType']);
    
        $args['id'] = $this['id'];
    
        if (isset($this['slug'])) {
            $args['slug'] = $this['slug'];
        }
    
        return $args;
    }
    
    /**
     * Create concatenated identifier string (for composite keys).
     *
     * @return String concatenated identifiers.
     */
    public function createCompositeIdentifier()
    {
        $itemId = $this['id'];
    
        return $itemId;
    }
    
    /**
     * Return lower case name of multiple items needed for hook areas.
     *
     * @return string
     */
    public function getHookAreaPrefix()
    {
        return 'classifieds.ui_hooks.classifieds';
    }

    /**
     * Returns an array of all related objects that need to be persited after clone.
     * 
     * @param array $objects The objects are added to this array. Default: array()
     * 
     * @return array of entity objects.
     */
    public function getRelatedObjectsToPersist(&$objects = array()) {
        return array();
     }

    
    /**
     * Post-Process the data after the entity has been constructed by the entity manager.
     * The event happens after the entity has been loaded from database or after a refresh call.
     *
     * Restrictions:
     *     - no access to entity manager or unit of work apis
     *     - no access to associations (not initialised yet)
     *
     * @see Classifieds_Entity_Classified::postLoadCallback()
     * @return boolean true if completed successfully else false.
     */
    protected function performPostLoadCallback()
    {
        // echo 'loaded a record ...';
        $currentFunc = FormUtil::getPassedValue('func', 'main', 'GETPOST', FILTER_SANITIZE_STRING);
        $usesCsvOutput = FormUtil::getPassedValue('usecsvext', false, 'GETPOST', FILTER_SANITIZE_STRING);
        
        // initialise the upload handler
        $uploadManager = new Classifieds_UploadHandler();
        $serviceManager = ServiceUtil::getManager();
        $controllerHelper = new Classifieds_Util_Controller($serviceManager);
        
        $this['id'] = (int) ((isset($this['id']) && !empty($this['id'])) ? DataUtil::formatForDisplay($this['id']) : 0);
        $this->formatTextualField('workflowState', $currentFunc, $usesCsvOutput, true);
        $this->formatTextualField('title', $currentFunc, $usesCsvOutput);
        $this->formatTextualField('kind', $currentFunc, $usesCsvOutput, true);
        $this->formatTextualField('description', $currentFunc, $usesCsvOutput);
        $this['price'] = (float) ((isset($this['price']) && !empty($this['price'])) ? DataUtil::formatForDisplay($this['price']) : 0.00);
        $this->formatTextualField('email', $currentFunc, $usesCsvOutput);
        $this->formatTextualField('fon', $currentFunc, $usesCsvOutput);
        if (!empty($this['picture'])) {
            try {
                $basePath = $controllerHelper->getFileBaseFolder('classified', 'picture');
            } catch (\Exception $e) {
                return LogUtil::registerError($e->getMessage());
            }
        
            $fullPath = $basePath .  $this['picture'];
            $this['pictureFullPath'] = $fullPath;
            $this['pictureFullPathURL'] = System::getBaseUrl() . $fullPath;
        
            // just some backwards compatibility stuff
            /*if (!isset($this['pictureMeta']) || !is_array($this['pictureMeta']) || !count($this['pictureMeta'])) {
                // assign new meta data
                $this['pictureMeta'] = $uploadManager->readMetaDataForFile($this['picture'], $fullPath);
            }*/
        }
        if (!empty($this['picture2'])) {
            try {
                $basePath = $controllerHelper->getFileBaseFolder('classified', 'picture2');
            } catch (\Exception $e) {
                return LogUtil::registerError($e->getMessage());
            }
        
            $fullPath = $basePath .  $this['picture2'];
            $this['picture2FullPath'] = $fullPath;
            $this['picture2FullPathURL'] = System::getBaseUrl() . $fullPath;
        
            // just some backwards compatibility stuff
            /*if (!isset($this['picture2Meta']) || !is_array($this['picture2Meta']) || !count($this['picture2Meta'])) {
                // assign new meta data
                $this['picture2Meta'] = $uploadManager->readMetaDataForFile($this['picture2'], $fullPath);
            }*/
        }
        $this['terms'] = (bool) $this['terms'];
    
        $this->prepareItemActions();
    
        return true;
    }
    
    /**
     * Formats a given textual field depending on it's actual kind of content.
     *
     * @param string  $fieldName     Name of field to be formatted.
     * @param string  $currentFunc   Name of current controller action.
     * @param string  $usesCsvOutput Whether the output is CSV or not (defaults to false).
     * @param boolean $allowZero     Whether 0 values are allowed or not (defaults to false).
     */
    protected function formatTextualField($fieldName, $currentFunc, $usesCsvOutput = false, $allowZero = false)
    {
        if ($currentFunc == 'edit') {
            // apply no changes when editing the content
            return;
        }
    
        $string = '';
        if (isset($this[$fieldName])) {
            if (!empty($this[$fieldName]) || ($allowZero && $this[$fieldName] == 0)) {
                $string = $this[$fieldName];
                if ($usesCsvOutput == 1) {
                    // strip only quotes when displaying raw output in CSV
                    $string = str_replace('"', '""', $string);
                } else {
                    if ($this->containsHtml($string)) {
                        $string = DataUtil::formatForDisplayHTML($string);
                    } else {
                        $string = DataUtil::formatForDisplay($string);
                        $string = nl2br($string);
                    }
                }
            }
        }
    
        $this[$fieldName] = $string;
    }
    
    /**
     * Checks whether any html tags are contained in the given string.
     * See http://stackoverflow.com/questions/10778035/how-to-check-if-string-contents-have-any-html-in-it for implementation details.
     *
     * @param $string string The given input string.
     *
     * @return boolean Whether any html tags are found or not.
     */
    protected function containsHtml($string)
    {
        return preg_match("/<[^<]+>/", $string, $m) != 0;
    }
    
    /**
     * Pre-Process the data prior to an insert operation.
     * The event happens before the entity managers persist operation is executed for this entity.
     *
     * Restrictions:
     *     - no access to entity manager or unit of work apis
     *     - no identifiers available if using an identity generator like sequences
     *     - Doctrine won't recognize changes on relations which are done here
     *       if this method is called by cascade persist
     *     - no creation of other entities allowed
     *
     * @see Classifieds_Entity_Classified::prePersistCallback()
     * @return boolean true if completed successfully else false.
     */
    protected function performPrePersistCallback()
    {
        // echo 'inserting a record ...';
        $this->validate();
    
        return true;
    }
    
    /**
     * Post-Process the data after an insert operation.
     * The event happens after the entity has been made persistant.
     * Will be called after the database insert operations.
     * The generated primary key values are available.
     *
     * Restrictions:
     *     - no access to entity manager or unit of work apis
     *
     * @see Classifieds_Entity_Classified::postPersistCallback()
     * @return boolean true if completed successfully else false.
     */
    protected function performPostPersistCallback()
    {
        // echo 'inserted a record ...';
        return true;
    }
    
    /**
     * Pre-Process the data prior a delete operation.
     * The event happens before the entity managers remove operation is executed for this entity.
     *
     * Restrictions:
     *     - no access to entity manager or unit of work apis
     *     - will not be called for a DQL DELETE statement
     *
     * @see Classifieds_Entity_Classified::preRemoveCallback()
     * @return boolean true if completed successfully else false.
     */
    protected function performPreRemoveCallback()
    {
        // delete workflow for this entity
        $workflow = $this['__WORKFLOW__'];
        if ($workflow['id'] > 0) {
            $result = (bool) DBUtil::deleteObjectByID('workflows', $workflow['id']);
            if ($result === false) {
                $dom = ZLanguage::getModuleDomain('Classifieds');
                return LogUtil::registerError(__('Error! Could not remove stored workflow. Deletion has been aborted.', $dom));
            }
        }
    
        return true;
    }
    
    /**
     * Post-Process the data after a delete.
     * The event happens after the entity has been deleted.
     * Will be called after the database delete operations.
     *
     * Restrictions:
     *     - no access to entity manager or unit of work apis
     *     - will not be called for a DQL DELETE statement
     *
     * @see Classifieds_Entity_Classified::postRemoveCallback()
     * @return boolean true if completed successfully else false.
     */
    protected function performPostRemoveCallback()
    {
        // echo 'deleted a record ...';
        $objectId = $this['id'];
        // initialise the upload handler
        $uploadManager = new Classifieds_UploadHandler();
    
        $uploadFields = array('picture', 'picture2');
        foreach ($uploadFields as $uploadField) {
            if (empty($this->$uploadField)) {
                continue;
            }
    
            // remove upload file (and image thumbnails)
            $uploadManager->deleteUploadFile('classified', $this, $uploadField, $objectId);
        }
    
        return true;
    }
    
    /**
     * Pre-Process the data prior to an update operation.
     * The event happens before the database update operations for the entity data.
     *
     * Restrictions:
     *     - no access to entity manager or unit of work apis
     *     - will not be called for a DQL UPDATE statement
     *     - changes on associations are not allowed and won't be recognized by flush
     *     - changes on properties won't be recognized by flush as well
     *     - no creation of other entities allowed
     *
     * @see Classifieds_Entity_Classified::preUpdateCallback()
     * @return boolean true if completed successfully else false.
     */
    protected function performPreUpdateCallback()
    {
        // echo 'updating a record ...';
        $this->validate();
    
        return true;
    }
    
    /**
     * Post-Process the data after an update operation.
     * The event happens after the database update operations for the entity data.
     *
     * Restrictions:
     *     - no access to entity manager or unit of work apis
     *     - will not be called for a DQL UPDATE statement
     *
     * @see Classifieds_Entity_Classified::postUpdateCallback()
     * @return boolean true if completed successfully else false.
     */
    protected function performPostUpdateCallback()
    {
        // echo 'updated a record ...';
        return true;
    }
    
    /**
     * Pre-Process the data prior to a save operation.
     * This combines the PrePersist and PreUpdate events.
     * For more information see corresponding callback handlers.
     *
     * @see Classifieds_Entity_Classified::preSaveCallback()
     * @return boolean true if completed successfully else false.
     */
    protected function performPreSaveCallback()
    {
        // echo 'saving a record ...';
        $this->validate();
    
        return true;
    }
    
    /**
     * Post-Process the data after a save operation.
     * This combines the PostPersist and PostUpdate events.
     * For more information see corresponding callback handlers.
     *
     * @see Classifieds_Entity_Classified::postSaveCallback()
     * @return boolean true if completed successfully else false.
     */
    protected function performPostSaveCallback()
    {
        // echo 'saved a record ...';
        return true;
    }
    

    /**
     * Returns the formatted title conforming to the display pattern
     * specified for this entity.
     */
    public function getTitleFromDisplayPattern()
    {
        $serviceManager = ServiceUtil::getManager();
        $listHelper = new Classifieds_Util_ListEntries($serviceManager);
    
        $formattedTitle = ''
                . $listHelper->resolve($this->getKind(), 'classified', 'kind')
                . ': '
                . $this->getTitle();
    
        return $formattedTitle;
    }

    /**
     * ToString interceptor implementation.
     * This method is useful for debugging purposes.
     */
    public function __toString()
    {
        return $this->getId();
    }

    /**
     * Clone interceptor implementation.
     * This method is for example called by the reuse functionality.
     * Performs a quite simple shallow copy.
     *
     * See also:
     * (1) http://docs.doctrine-project.org/en/latest/cookbook/implementing-wakeup-or-clone.html
     * (2) http://www.php.net/manual/en/language.oop5.cloning.php
     * (3) http://stackoverflow.com/questions/185934/how-do-i-create-a-copy-of-an-object-in-php
     * (4) http://www.pantovic.com/article/26/doctrine2-entity-cloning
     */
    public function __clone()
    {
        // If the entity has an identity, proceed as normal.
        if ($this->id) {
            // unset identifiers
            $this->setId(0);
    
            // init validator
            $this->initValidator();
    
            // reset Workflow
            $this->resetWorkflow();
    
            $this->setCreatedDate(null);
            $this->setCreatedUserId(null);
            $this->setUpdatedDate(null);
            $this->setUpdatedUserId(null);
    
        }
        // otherwise do nothing, do NOT throw an exception!
    }
}
