<?php
/**
 * Classifieds.
 *
 * @copyright Ralf Koester (Rallek)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Classifieds
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing classified categories.
 *
 * This is the base category class for classified entities.
 */
class Classifieds_Entity_Base_ClassifiedCategory extends Zikula_Doctrine2_Entity_EntityCategory
{
    /**
     * @ORM\ManyToOne(targetEntity="Classifieds_Entity_Classified", inversedBy="categories")
     * @ORM\JoinColumn(name="entityId", referencedColumnName="id")
     * @var Classifieds_Entity_Classified
     */
    protected $entity;

    /**
     * Get reference to owning entity.
     *
     * @return Classifieds_Entity_Classified
     */
    public function getEntity()
    {
        return $this->entity;
    }

    /**
     * Set reference to owning entity.
     *
     * @param Classifieds_Entity_Classified $entity
     */
    public function setEntity(/*Classifieds_Entity_Classified */$entity)
    {
        $this->entity = $entity;
    }
}
