<?php
/**
 * Classifieds.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Classifieds
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the concrete validation class for classified entities.
 */
class Classifieds_Entity_Validator_Classified extends Classifieds_Entity_Validator_Base_Classified
{
    // here you can add custom validation methods or override existing checks
}
