<?php
/**
 * Classifieds.
 *
 * @copyright Ralf Koester (Rallek)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Classifieds
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * This class provides object meta data for the Tag module.
 */
class Classifieds_TaggedObjectMeta_Classifieds extends Classifieds_TaggedObjectMeta_Base_Classifieds
{
    // feel free to extend the tag support here
}
