<?php
/**
 * Classifieds.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Classifieds
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Item selector plugin implementation class.
 */
class Classifieds_Form_Plugin_ItemSelector extends Classifieds_Form_Plugin_Base_ItemSelector
{
    // feel free to add your customisation here
}
