<?php
/**
 * Classifieds.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Classifieds
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the base validation class for classified entities.
 */
class Classifieds_Entity_Validator_Base_Classified extends Classifieds_Validator
{
    /**
     * Performs all validation rules.
     *
     * @return mixed either array with error information or true on success
     */
    public function validateAll()
    {
        $errorInfo = array('message' => '', 'code' => 0, 'debugArray' => array());
        $dom = ZLanguage::getModuleDomain('Classifieds');
        if (!$this->isValidInteger('id')) {
            $errorInfo['message'] = __f('Error! Field value may only contain digits (%s).', array('id'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotLongerThan('id', 9)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('id', 9), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('workflowState')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('workflow state'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('title', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('title', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('title')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('title'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('kind')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('kind'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('description', 2000)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('description', 2000), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('description')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('description'), $dom);
            return $errorInfo;
        }
        if (!$this->isValidNumber('price')) {
            $errorInfo['message'] = __f('Error! Field value must be numeric (%s).', array('price'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotLongerThan('price', 12)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('price', 12), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('email', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('email', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('email')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('email'), $dom);
            return $errorInfo;
        }
        if (!$this->isValidEmail('email')) {
            $errorInfo['message'] = __f('Error! Field value must be a valid email address (%s).', array('email'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('fon', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('fon', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('picture', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('picture', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isValidDateTime('enddate')) {
            $errorInfo['message'] = __f('Error! Field value must be a valid datetime (%s).', array('enddate'), $dom);
            return $errorInfo;
        }
        if (!$this->isDateTimeInFuture('enddate', true)) {
            $errorInfo['message'] = __f('Error! Field value must be a date in the future (%s).', array('enddate'), $dom);
            return $errorInfo;
        }
        if (!$this->isValidBoolean('terms')) {
            $errorInfo['message'] = __f('Error! Field value must be a valid boolean (%s).', array('terms'), $dom);
            return $errorInfo;
        }
        if ($this->entity['startdate'] > $this->entity['enddate']) {
            $errorInfo['message'] = __f('Error! The start date (%1$s) must be before the end date (%2$s).', array('startdate', 'enddate'), $dom);
            return $errorInfo;
        }
    
        return true;
    }
    
    /**
     * Check for unique values.
     *
     * This method determines if there already exist classifieds with the same classified.
     *
     * @param string $fieldName The name of the property to be checked
     * @return boolean result of this check, true if the given classified does not already exist
     */
    public function isUniqueValue($fieldName)
    {
        if ($this->entity[$fieldName] == '') {
            return false;
        }
    
        $entityClass = 'Classifieds_Entity_Classified';
        $serviceManager = ServiceUtil::getManager();
        $entityManager = $serviceManager->getService('doctrine.entitymanager');
        $repository = $entityManager->getRepository($entityClass);
    
        $excludeid = $this->entity['id'];
    
        return $repository->detectUniqueState($fieldName, $this->entity[$fieldName], $excludeid);
    }
    
    /**
     * Get entity.
     *
     * @return Zikula_EntityAccess
     */
    public function getEntity()
    {
        return $this->entity;
    }
    
    /**
     * Set entity.
     *
     * @param Zikula_EntityAccess $entity.
     *
     * @return void
     */
    public function setEntity(Zikula_EntityAccess $entity = null)
    {
        $this->entity = $entity;
    }
    
}
