<?php
/**
 * Classifieds.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Classifieds
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * This handler class handles the page events of the Form called by the classifieds_user_edit() function.
 * It collects common functionality required by different object types.
 */
class Classifieds_Form_Handler_User_Edit extends Classifieds_Form_Handler_User_Base_Edit
{
    // feel free to extend the base handler class here
}
