<?php
/**
 * Classifieds.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Classifieds
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Selection api implementation class.
 */
class Classifieds_Api_Selection extends Classifieds_Api_Base_Selection
{
    // feel free to extend the selection api here
}
