<?php
/**
 * Classifieds.
 *
 * @copyright Ralf Koester (Rallek)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Classifieds
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Upload handler implementation class.
 */
class Classifieds_UploadHandler extends Classifieds_Base_UploadHandler
{
    // feel free to add your upload handler enhancements here
    public function __construct()
    {
        $this->allowedObjectTypes = array('classified');
        $this->imageFileTypes = array('gif', 'jpeg', 'jpg', 'png', 'swf');
        $this->forbiddenFileTypes = array('cgi', 'pl', 'asp', 'phtml', 'php', 'php3', 'php4', 'php5', 'exe', 'com', 'bat', 'jsp', 'cfm', 'shtml');
        $this->allowedFileSizes['picture'] = ModUtil::getVar('Classiefieds', 'pictureFileSize' 102400);
		$this->allowedFileSizes['picture2'] = ModUtil::getVar('Classiefieds', 'pictureFileSize' 102400);
    }
}
