<?php
/**
 * Classifieds.
 *
 * @copyright Ralf Koester (Rallek)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Classifieds
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de) at Sun Feb 02 11:46:55 CET 2014.
 */

/**
 * Version information implementation class.
 */
class Classifieds_Version extends Classifieds_Base_Version
{
    // custom enhancements can go here
}
