<?php
/**
 * Classifieds.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Classifieds
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Bootstrap called when application is first initialised at runtime.
 *
 * This is only called once, and only if the core has reason to initialise this module,
 * usually to dispatch a controller request or API.
 *
 * For example you can register additional AutoLoaders with ZLoader::addAutoloader($namespace, $path)
 * whereby $namespace is the first part of the PEAR class name
 * and $path is the path to the containing folder.
 */
// initialise doctrine extension listeners
$helper = ServiceUtil::getService('doctrine_extensions');
$helper->getListener('timestampable');
$helper->getListener('standardfields');
clfsPerformRegularAmendments();

function clfsPerformRegularAmendments()
{
    $currentFunc = FormUtil::getPassedValue('func', 'main', 'GETPOST', FILTER_SANITIZE_STRING);
    if ($currentFunc == 'edit') {
        return;
    }

    $randProbability = mt_rand(1, 1000);

    if ($randProbability < 850) {
        return;
    }

    $entityManager = ServiceUtil::getService('doctrine.entitymanager');

    // update for classifieds becoming archived
    $entityClass = 'Classifieds_Entity_Classified';
    $repository = $entityManager->getRepository($entityClass);
    $repository->archiveObjects();
}

