<?php
/**
 * Classifieds.
 *
 * @copyright Ralf Koester (Rallek)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Classifieds
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Utility implementation class for image helper methods.
 */
class Classifieds_Util_Image extends Classifieds_Util_Base_Image
{
/**
     * This method returns an Imagine preset for the given arguments.
     *
     * @param string $objectType Currently treated entity type.
     * @param string $fieldName  Name of upload field.
     * @param string $presetName Name of desired preset.
     * @param string $context    Usage context (allowed values: controllerAction, api, actionHandler, block, contentType).
     * @param array  $args       Additional arguments.
     *
     * @return SystemPlugin_Imagine_Preset The selected preset.
     */
    public function getCustomPreset($objectType = '', $fieldName = '', $presetName = '', $context = '', $args = array())
    {
        $presetData = array(
            'width'     => 100,      // thumbnail width in pixels
            'height'    => 100,      // thumbnail height in pixels
            'mode'      => 'inset',  // inset or outbound
            'extension' => null      // file extension for thumbnails (jpg, png, gif; null for original file type)
        );
    
        if ($presetName == $this->name . '_ajax_autocomplete') {
            $presetData['width'] = 100;
            $presetData['height'] = 80;
        } elseif ($presetName == $this->name . '_relateditem') {
            $presetData['width'] = 50;
            $presetData['height'] = 40;
        } elseif ($context == 'controllerAction') {
            if ($args['action'] == 'view') {
                $presetData['width'] = ModUtil::getVar('Classifieds', 'thumbPictureWidth', 64); //32;
                $presetData['height'] = ModUtil::getVar('Classifieds', 'thumbPictureHeight', 64); //20;
            } elseif ($args['action'] == 'display') {
                $presetData['width'] = ModUtil::getVar('Classifieds', 'pictureWidth', 200); //250;
                $presetData['height'] = ModUtil::getVar('Classifieds', 'pictureHeight', 200); //150;
            }
        }
    
        $preset = new SystemPlugin_Imagine_Preset($presetName, $presetData);
    
        return $preset;
    }
}
