<?php
/**
 * Classifieds.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Classifieds
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing classified categories.
 *
 * This is the concrete category class for classified entities.
* @ORM\Entity(repositoryClass="Classifieds_Entity_Repository_ClassifiedCategory")
   * @ORM\Table(name="clfs_classified_category",
   *     uniqueConstraints={
   *         @ORM\UniqueConstraint(name="cat_unq", columns={"registryId", "categoryId", "entityId"})
   *     }
   * )
 */
class Classifieds_Entity_ClassifiedCategory extends Classifieds_Entity_Base_ClassifiedCategory
{
    // feel free to add your own methods here
}
